### ISSUE TITLE
unwanted slide appearing

### ISSUE THREAD

**Issue by nithinmkp** [alexeygumirov/pandoc-beamer-how-to#3]
While using this template, an unwanted slide containing section titles appear in addition to the actual table of contents slide. how to get rid of it?
![Untitled](https://user-images.githubusercontent.com/65053643/117689867-d2f09800-b1d7-11eb-8f84-94f85f11a6a9.png)

**Comment by alexeygumirov** [comment]
I think it is MD formatting issue.
