### ISSUE TITLE
How to add normal text after a block?

### ISSUE THREAD

**Issue by Eloitor** [alexeygumirov/pandoc-beamer-how-to#5]
Hi,
I would like to have a slide which contains a block surrounded by normal text.

For example:
```
# Example slide

Text before block

## My block
Text inside block

Now I want this text to be outside the block
```
Do you know how can I do this?

Edit:
I found the solution:
<https://github.com/jgm/pandoc/issues/2957#issuecomment-340855258>

I think you could add this to this guide... It is a common thing to need when preparing slides.

**Comment by alexeygumirov** [comment]
Thanks a lot. Did you try it with this version of Pandoc?

**Comment by Eloitor** [comment]
I have pandoc 2.16.2 ...
By the way, I created [this repo](https://github.com/Eloitor/pandoc-presentation-template) with a makefile which compiles the markdown in `src/` to a beamer presentation in `output/`, some handouts versions, and a presentation with speaker notes.

**Comment by alexeygumirov** [comment]
Thanks a lot!
